[package]
name = "pura_lingua_compiler4middle_ir_proc_macro_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.110"
proc-macro-crate = "3.3.0"

[lints]
workspace = true
