[package]
name = "pura_lingua_compiler4middle_ir_token_proc_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"

proc_macro_utils = { workspace = true }

[lib]
proc-macro = true
